language: python
python:
  - "2.6"
  - "2.7"
  - "3.5"
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.dev.txt"

# command to run tests
script: pytest --cov=pudb test

after_success:
  - eval "codecov --token=c15f6318-87e5-4fce-a9f7-2ed1358e65c3"

sudo: false